export const UPDATE_MAIN_PAGE = 'UPDATE_MAIN_PAGE'
export const MAIN_PAGE_UPDATE_SUCCEEDED = 'MAIN_PAGE_UPDATE_SUCCEEDED'
export const MAIN_PAGE_UPDATE_FAILED = 'MAIN_PAGE_UPDATE_FAILED'
export const OPEN_SIDE_MENU = 'OPEN_SIDE_MENU'
